# Generated by Django 6.0.2 on 2026-02-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('en', 'En'), ('ru', 'Ru'), ('fr', 'Fr')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='lang',
            field=models.CharField(choices=[('en', 'En'), ('ru', 'Ru'), ('fr', 'Fr')], max_length=10),
        ),
    ]
