# Generated by Django 6.0.2 on 2026-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_word_source_alter_wordtranslation_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('uz', 'Uz'), ('en', 'En'), ('ru', 'Ru')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uz'), ('en', 'En'), ('ru', 'Ru')], max_length=10),
        ),
    ]
