# Generated by Django 6.0.2 on 2026-02-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_word_source_alter_wordtranslation_lang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='EntryWord',
        ),
    ]
